framework:
  asset_mapper:
    importmap_polyfill: false
    missing_import_mode: strict
    paths:
      - assets/
sensiolabs_typescript:
  source_dir: ["%kernel.project_dir%/assets/controllers"]
when@prod:
  framework:
    asset_mapper:
      missing_import_mode: warn
