twig:
  file_name_pattern: "*.twig"
  form_themes: ["shared/form.html.twig"]
  globals:
    csp: '@App\Infrastructure\Shared\ContentSecurityPolicyGenerator'
    days:
      1: lundi
      2: mardi
      3: mercredi
      4: jeudi
      5: vendredi
      6: samedi
      7: dimanche
    units: "%app.units%"
when@test:
  twig:
    strict_variables: true
