twig:
  file_name_pattern: "*.twig"
  globals:
    csp: '@App\Infrastructure\Shared\ContentSecurityPolicyGenerator'
    days:
      1: lundi
      2: mardi
      3: mercredi
      4: jeudi
      5: vendredi
      6: samedi
      7: dimanche
    units:
      pinch: pincée
      tbsp.: c.-à-s.
      tsp.: c.-à-c.
when@test:
  twig:
    strict_variables: true
