controllers:
  resource:
    namespace: App\Presentation
    path: ../src/Presentation/
  type: attribute
manifest:
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    headers:
      Content-Type: application/manifest+json
    maxAge: 604_800
    template: manifest.json.twig
  methods: GET
  path: /manifest.webmanifest
  stateless: true
