parameters:
  .container.dumper.inline_factories: true
services:
  _defaults:
    autoconfigure: true
    autowire: true
  App\:
    exclude:
      - "../src/Domain/Menu/Day.php"
      - "../src/Domain/Menu/Menu.php"
      - "../src/Kernel.php"
    resource: "../src/"
  Symfony\Component\Dotenv\Command\DotenvDumpCommand: ~
when@test:
  services:
    App\Tests\Fixtures\:
      autoconfigure: true
      autowire: true
      resource: "../tests/Fixtures"
