name: Build
on:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - uses: actions/checkout@v4
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-php-dev-${{ hashFiles('**/composer.lock') }}
          path: vendor
          restore-keys: ${{ runner.os }}-php-dev-
      - name: Install Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --quiet
      - name: Cache npm packages
        id: npm-cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          path: node_modules
          restore-keys: ${{ runner.os }}-npm-
      - name: Install npm dependencies
        run: npm install
      - name: Check formatting
        run: npx prettier . --check
      - name: Lint container
        run: php bin/console --env=prod lint:container
      - name: Lint templates
        run: php bin/console --env=prod lint:twig
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
      - uses: actions/checkout@v4
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          path: vendor
          restore-keys: ${{ runner.os }}-php-
      - name: Install Composer dependencies
        run: composer install --classmap-authoritative --no-ansi --no-dev --no-interaction --no-scripts --no-progress --prefer-dist --quiet
      - name: Compile assets
        run: php bin/console asset-map:compile
      - name: Cleanup
        run: |
          rm -rf .git .github .gitignore
          rm -rf package.json package-lock.json
          rm -rf var
          rm -rf tests
          rm -rf .prettierrc
          rm -rf assets
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          include-hidden-files: true
          name: build
          path: .
